dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
 
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  assets:
    - assets/images/
    - assets/files/
  uses-material-design: true
name: flutter_application_1
publish_to: none
version: 1.0.0+1
